### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ericwuu** [divanov11/Django-To-Do-list-with-user-authentication#12]
C:\Users\wue\Documents\GitHub\Django-To-Do-list-with-user-authentication>python manage.py
Traceback (most recent call last):
  File "C:\Users\wue\Documents\GitHub\Django-To-Do-list-with-user-authentication\manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

**Comment by LexxLuey** [comment]
Did you pip install Django in your virtual environment?

**Comment by jagtaprathmesh19** [comment]
or you can create a fresh virtual environment?

**Comment by sabbanishailaja** [comment]
File "C:\Users\ssabbani\Todolist\myvenv\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'task'
iam getting this error

**Comment by jagtaprathmesh19** [comment]
have you import Task module correctly, just check that .

**Comment by sabbanishailaja** [comment]
where should i look in the urls.py?

**Comment by sabbanishailaja** [comment]
from django.contrib import admin
from .models import Task

admin.site.register(Task) did u mean this

**Comment by jagtaprathmesh19** [comment]
> from django.contrib import admin from .models import Task
> 
> admin.site.register(Task) did u mean this

you have to mention this in **admin.py** file

**Comment by jagtaprathmesh19** [comment]
first of all, check the name is it a task or tasks?
